### ISSUE TITLE
LifePredictor problem

### ISSUE THREAD

**Issue by Intekai** [VedAstro/VedAstro#131]
https://vedastro.org/LifePredictor not work fine
![Screenshot 2024-06-11 144616](https://github.com/VedAstro/VedAstro/assets/68114285/673d633e-38a5-4102-9953-78e6028c33df)

**Comment by sengiv** [comment]
Thank you very much for the report. 🙏
At 1st glance it looks like the time range is too short. 🗓️

I just did a chart generate, and it worked fine (basically i can't reproduce on my side)

Did you try generate other charts like "Steve Jobs", same error?

There is 2 possibilities here,
1. birth time got corrupt during creation (try creating new horosope profile again)
2. Server crashed on 1st run, saved the crashed chart in cache, and is showing you that instead of calculating new (maybe future I'll add option to skip cache use, for now just change the time range or recreate new profile)
3. Double check the inputed time range

Let me know if this helps 🤞

**Comment by Intekai** [comment]
![image](https://github.com/VedAstro/VedAstro/assets/68114285/04df597b-0ba0-44d7-a4ad-8493920d2902)

Time Range is Life i try with new istance but not work, i have changed Person and i have loaded my data but not work
